parameters:
    # maybe put this into the database later
    retromat.plan.titles:
        en:
            sequence_of_groups:
                0:  [ 0,     1,  3,   5, 6, 7, 8,   10     ]
                1:  [ 0,       2,  4, 5, 6, 7,    9        ]
                2:  [ 0,     1,  3,   5, 6, 7, 8,   10     ]
                3:  [ 0,       2,  4, 5, 6, 7,    9        ]
                4:  [ 0,     1,       5,    7,          11 ]
                5:  [ 0,     1,       5,       8,       11 ]
                6:  [ 0,       2,     5,    7,          11 ]
                7:  [ 0,       2,     5,       8,       11 ]
                8:  [ 0, 12, 1,  3,   5, 6,          10    ]
                9:  [ 0, 12,   2,  4, 5, 6,       9        ]
                10: [ 0, 12, 1,  3,   5, 6,          10    ]
                11: [ 0, 12,   2,  4, 5, 6,       9        ]
                12: [ 0, 13,          5, 6, 7, 8,    10    ]
                13: [ 0, 13,          5, 6, 7,    9        ]
                14: [ 0, 13,          5, 6, 7, 8,    10    ]
                15: [ 0, 13,          5, 6, 7,    9        ]
    
            groups_of_terms:
                # "" as first element marks the group as optional (may be skipped to satisfy length constraints)
                0:  ["Retromat:"]
                1:  ["", "Kanban", "Lean"] # either 1+3 (without iterations) or 2+4 (with iteration)
                2:  ["", "Agile", "Scrum", "XP", "Extreme Programming"]
                3:  ["", "Release", "Project", "Program", "Process", "Team", "Over All"]
                4:  ["", "Release", "Project", "Program", "Process", "Team", "Over All", "Iteration", "Sprint", "Cycle"]
                5:  ["Retrospective", "Retro", "Post Mortem", "A3", "Lessons Learned", "Reflection", "Inspect & Adapt", "Analysis"]
                6:  ["", "Meeting", "Event", "Discussion", "Ceremony"]
                7:  ["", "Plan", "Agenda", "Structure", "Experiment"]
                8:  ["", "Ideas", "Inspiration", "Example"]
                9:  ["", "Activities"] # either 9 or 10
                10: ["", "with 5 Activities", "with 5 Stages", "with 5 Steps", "with 5 Ideas", "with 5 Activity Ideas", "with 5 Activity Examples"]
                11: ["", "Generator", "Tool", "Guide", "Directory"]
                12: ["", "Plan Your", "Organize Your", "Create Your", "Prepare Your"]
                13: ["", "Scrum Master Tools:", "ScrumMaster Toolbox:", "Facilitator's Tools:", "Facilitation Toolbox:"]

        de:
            sequence_of_groups:
                0:  [ 0,     1,    3,    5, 6, 7, 8,    10     ]
                1:  [ 0,        2,    4, 5, 6, 7,    9         ]
                2:  [ 0,     1,    3,    5, 6, 7, 8,    10     ]
                3:  [ 0,        2,    4, 5, 6, 7,    9         ]
                4:  [ 0,     1,          5,    7,           11 ]
                5:  [ 0,     1,          5,       8,        11 ]
                6:  [ 0,        2,       5,    7,           11 ]
                7:  [ 0,        2,       5,       8,        11 ]
                8:  [ 0, 12, 1,    3,    5, 6,           10    ]
                9:  [ 0, 12,    2,    4, 5, 6,        9        ]
                10: [ 0, 12, 1,    3,    5, 6,           10    ]
                11: [ 0, 12,    2,    4, 5, 6,        9        ]
                12: [ 0, 13,             5, 6, 7, 8,    10     ]
                13: [ 0, 13,             5, 6, 7,    9         ]
                14: [ 0, 13,             5, 6, 7, 8,    10     ]
                15: [ 0, 13,             5, 6, 7,    9         ]

            groups_of_terms:
                # "" as first element marks the group as optional (may be skipped to satisfy length constraints)
                0: ["Retromat:"]
                1: ["", "Kanban", "Lean"] # entweder 1 + 3 (ohne Iterationen) oder 2 + 4 (mit Iterationen)
                2: ["", "Agile", "Scrum", "XP", "Extreme Programming"]
                3: ["", "Release", "Projekt", "Programm", "Prozess", "Team", "Gesamt"]
                4: ["", "Release", "Projekt", "Programm", "Prozess", "Team", "Gesamt", "Iterations", "Sprint", "Zyklus"]
                5: ["Retrospektive", "Retro", "Post Mortem", "A3", "Lessons Learned", "Reflexion", "Rückblick", "Rückschau", "Inspect & Adapt", "Analyse", "Qualitätszirkel"]
                6: ["", "Meeting", "Treffen", "Diskussion", "Zeremonie"]
                7: ["", "Plan", "Agenda", "Struktur", "Experiment"]
                8: ["", "Ideen", "Inspiration", "Beispiel"]
                9: ["", "Aktivitäten"] # entweder 9 oder 10
                10: ["", "mit 5 Aktivitäten", "mit 5 Stufen", "in 5 Stufen", "mit 5 Schritten", "in 5 Schritten", "mit 5 Ideen", "mit 5 Aktivitätsideen", "mit 5 Aktivitätsbeispielen"]
                11: ["", "Generator", "Tool", "Werkzeug", "Anleitung", "Verzeichnis", "Leitfaden"]
                12: ["", "Plane Dein(e)", "Organisiere Dein(e)", "Erstelle Dein(e)", "Vorbereitung für Dein(e)"]
                13: ["", "Scrum Master Tools:", "ScrumMaster Toolbox:", "Werkzeugkoffer für Moderatoren:", "Moderatoren Toolbox:"]

        ru:
            sequence_of_groups:
                0:  [ 0,     1,  3,   5, 6, 7, 8,   10     ]
                1:  [ 0,       2,  4, 5, 6, 7,    9        ]
                2:  [ 0,     1,  3,   5, 6, 7, 8,   10     ]
                3:  [ 0,       2,  4, 5, 6, 7,    9        ]
                4:  [ 0,     1,       5,    7,          11 ]
                5:  [ 0,     1,       5,       8,       11 ]
                6:  [ 0,       2,     5,    7,          11 ]
                7:  [ 0,       2,     5,       8,       11 ]
                8:  [ 0, 12, 1,  3,   5, 6,          10    ]
                9:  [ 0, 12,   2,  4, 5, 6,       9        ]
                10: [ 0, 12, 1,  3,   5, 6,          10    ]
                11: [ 0, 12,   2,  4, 5, 6,       9        ]
                12: [ 0, 13,          5, 6, 7, 8,    10    ]
                13: [ 0, 13,          5, 6, 7,    9        ]
                14: [ 0, 13,          5, 6, 7, 8,    10    ]
                15: [ 0, 13,          5, 6, 7,    9        ]

            groups_of_terms:
                # "" as first element marks the group as optional (may be skipped to satisfy length constraints)
                0: ["Retromat:"]
                1: ["", "Kanban", "Lean"] # either 1+3 (without iterations) or 2+4 (with iteration)
                2: ["", "Agile", "Scrum", "XP", "Extreme Programming"]
                3: ["", "Release", "Project", "Program", "Process", "Team", "Over All"]
                4: ["", "Release", "Project", "Program", "Process", "Team", "Over All", "Iteration", "Sprint", "Cycle"]
                5: ["Ретроспектива", "Ретро", "Post Mortem", "A3", "Извлеченные уроки", "Отражение", "Проверка и адаптация", "Анализ"]
                6: ["", "Встреча", "Событие", "Обсуждение", "Церемония"]
                7: ["", "План", "Повестка дня", "Структура", "Эксперимент"]
                8: ["", "Идеи", "Вдохновение", "Пример"]
                9: ["", "Activities"] # either 9 or 10
                10: ["", "с 5 действиями", "с 5 этапами", "с 5 шагами", "с 5 идеями", "с 5 видами деятельности", "с 5 примерами действий"]
                11: ["", "Генератор", "Инструмент", "Руководство", "Справочник"]
                12: ["", "Plan Your", "Organize Your", "Create Your", "Prepare Your"]
                13: ["", "Scrum Master Tools:", "ScrumMaster Toolbox:", "Инструменты фасилитатора:", "Инструментарий помощи:"]
