imports:
    - { resource: retromat/models.yaml }
    - { resource: retromat/commands.yaml }
    - { resource: retromat/fixtures.yaml }
    - { resource: retromat/subscriber.yaml }

parameters:
    locale: 'en'
    knp.doctrine_behaviors.translatable_subscriber.translatable_fetch_method: EAGER
    knp.doctrine_behaviors.translatable_subscriber.translation_fetch_method: EAGER

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'
            - '../src/Command/'

    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    App\Model\Activity\Expander\ActivityExpander:
        arguments:
            $sources: '%retromat.activity.source%'

    App\Model\Importer\Activity\ActivityReader:
        arguments:
            $activityFileNames: '%retromat.activity.import.file_names%'

    App\Model\Importer\Activity\ActivityImporter:
        public: true
        arguments:
            $locales: '%retromat.activity.import.languages.whitelist%'

    App\Model\Plan\TitleChooser:
        arguments:
            $titleParts: '%retromat.plan.titles%'
            $maxLengthIncludingPlanId: 60

    App\Model\Plan\TitleIdGenerator:
        arguments:
            $titleParts: '%retromat.plan.titles%'

    App\Model\Plan\TitleRenderer:
        arguments:
            $parts: '%retromat.plan.titles%'

    App\Model\User\UserResetPasswordManager:
        arguments:
            $resetRequestLifetime: 3600

    App\Model\User\Generator\UserResetPasswordTokenGenerator:
        arguments:
            $signingKey: NpGqMRwfIA0Eg6Usd

    App\Model\User\Mailer\UserResetPasswordMailer:
        arguments:
            $from: '%env(MAILER_FROM_ADDRESS)%'
            $subject: 'Passwort Reset'
            $template: 'user/reset-password/email/reset-password-request.txt.twig'

    Hackzilla\PasswordGenerator\Generator\ComputerPasswordGenerator:
        class: Hackzilla\PasswordGenerator\Generator\ComputerPasswordGenerator

    Presta\SitemapBundle\Service\UrlContainerInterface:
        class: Presta\SitemapBundle\Service\UrlContainerInterface
