# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'en'
    knp.doctrine_behaviors.translatable_subscriber.translatable_fetch_method: EAGER
    knp.doctrine_behaviors.translatable_subscriber.translation_fetch_method: EAGER

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    # Retromat

    array_to_object_mapper:
        class: App\Model\Importer\ArrayToObjectMapper
    retromat.activity_by_phase:
        class: App\Model\Activity\ActivityByPhase
        arguments: ["@doctrine.orm.entity_manager"]
    retromat.activity_source_expander:
        class: App\Model\Activity\ActivitySourceExpander
        arguments: ["%retromat.activity.source%"]
    retromat.activity_reader:
        class: App\Model\Importer\Activity\ActivityReader
        arguments: [~, "%retromat.activity.import.file_names%"]
    retromat.activity_importer:
        class: App\Model\Importer\Activity\ActivityImporter
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@retromat.activity_reader"
            - "@array_to_object_mapper"
            - "@validator"
            - "%retromat.activity.import.languages.whitelist%"
    retromat.color_varation:
        class: App\Model\Twig\ColorVariation
    retromat.plan.description_renderer:
        class: App\Model\Plan\DescriptionRenderer
    retromat.plan.plan_id_generator:
        class: App\Model\Sitemap\PlanIdGenerator
        arguments: ["@retromat.activity_by_phase"]
    retromat.plan.title_chooser:
        class: App\Model\Plan\TitleChooser
        arguments: ["%retromat.plan.titles%", "@retromat.plan.title_renderer", 60]
    retromat.plan.title_id_generator:
        class: App\Model\Plan\TitleIdGenerator
        arguments: ["%retromat.plan.titles%"]
    retromat.plan.title_renderer:
        class: App\Model\Plan\TitleRenderer
        arguments: ["%retromat.plan.titles%"]

