imports:
    - { resource: retromat/models.yaml }
    - { resource: retromat/commands.yaml }

parameters:
    locale: 'en'
    knp.doctrine_behaviors.translatable_subscriber.translatable_fetch_method: EAGER
    knp.doctrine_behaviors.translatable_subscriber.translation_fetch_method: EAGER

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'
            - '../src/Command/'

    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    App\Model\Activity\ActivitySourceExpander:
        arguments:
            $sources: '%retromat.activity.source%'

    App\Model\Importer\Activity\ActivityReader:
        arguments:
            $activityFileNames: '%retromat.activity.import.file_names%'

    App\Model\Importer\Activity\ActivityImporter:
        arguments:
            $locales: '%retromat.activity.import.languages.whitelist%'

    App\Model\Plan\TitleChooser:
        arguments:
            $titleParts: '%retromat.plan.titles%'
            $maxLengthIncludingPlanId: 60

    App\Model\Plan\TitleIdGenerator:
        arguments:
            $titleParts: '%retromat.plan.titles%'

    App\Model\Plan\TitleRenderer:
        arguments:
            $parts: '%retromat.plan.titles%'

    # @todo add missing redis and sitemap services
