services:
  - redis

addons:
  mariadb: '10.3'

language: php

php:
    - 8.0

before_install:
    - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

env:
  - APP_ENV=test

install:
    - composer install --working-dir=backend

before_script:
    - mv backend/.env.travis-before backend/.env
    - php backend/bin/console doctrine:database:create
    - php backend/bin/console doctrine:migrations:migrate --no-interaction
    - backend/bin/travis-ci/generate-templates-from-retromat-v1.sh

script:
    - backend/vendor/bin/phpunit -c backend

deploy:
    on:
        branch: master
        condition: $TRAVIS_PHP_VERSION = 8.0
    skip_cleanup: true
    provider: script
    script: /bin/true

before_deploy:
    - mkdir -p .travis/
    - openssl aes-256-cbc -md sha256 -d -a -in backend/bin/travis-ci/rsa_travis_timon.enc -out .travis/rsa_travis_timon -k $travis_key
    - chmod 600 .travis/rsa_travis_timon
    - eval "$(ssh-agent -s)"
    - ssh-add .travis/rsa_travis_timon
    - rm -rf .travis/
    - openssl aes-256-cbc -md sha256 -d -a -in backend/.env.cordelia.enc -out backend/.env -k $travis_key
    - php backend/bin/travis-ci/deployU7.php $TRAVIS_COMMIT
    - ssh-agent -k

notifications:
    email:
        on_success: always
        on_failure: always
        recipients:
            - timon.fiddike@agile.coach
            - corinna@finding-marbles.com
