version: '3.1'

services:

 db:
  image: mariadb
  ports:
   - 3306:3306
  environment:
   MYSQL_ROOT_PASSWORD: PaSsWoRd
  networks:
   - retromat

 redis:
  image: redis
  ports:
   - 6379:6379
  networks:
   - retromat

 phpmyadmin:
  image: phpmyadmin/phpmyadmin
  links:
   - db:db
  ports:
   - 8181:80
  networks:
   - retromat

networks:
 retromat:
  driver: bridge
