services:
 httpd:
  build:
   context: .
   dockerfile: ./backend/docker/httpd/Dockerfile
  volumes:
   - ./backend/public:/app/backend/public
  depends_on:
   - php-fpm
  ports:
   - ${RETROMAT_HTTPD_PORT:-8080}:80
  env_file:
   - docker-ports.env
  networks:
   - retromat
 php-fpm:
  build:
   context: .
   dockerfile: ./backend/docker/php-fpm/Dockerfile
  volumes:
   - .:/app
  depends_on:
   - db
  networks:
   - retromat
 db:
  image: mariadb
  ports:
   - ${RETROMAT_DB_PORT:-3306}:3306
  environment:
   MYSQL_ROOT_PASSWORD: PaSsWoRd
  env_file:
   - docker-ports.env
  networks:
   - retromat
 redis:
  image: redis
  ports:
   - ${RETROMAT_REDIS_PORT:-6379}:6379
  env_file:
   - docker-ports.env
  networks:
   - retromat
 phpmyadmin:
  image: phpmyadmin/phpmyadmin
  links:
   - db:db
  ports:
   - ${RETROMAT_PHPMYADMIN_PORT:-8181}:80
  env_file:
   - docker-ports.env
  networks:
   - retromat
 mailcatcher:
  image: schickling/mailcatcher
  ports:
   - ${RETROMAT_MAILCATCHER_SMTP_PORT:-1025}:1025
   - ${RETROMAT_MAILCATCHER_WEB_PORT:-1080}:1080
  env_file:
   - docker-ports.env
  networks:
   - retromat
networks:
 retromat:
  driver: bridge
