version: '3.1'

services:
 nginx:
  build:
   context: .
   dockerfile: ./backend/docker/nginx/Dockerfile
  volumes:
   - ./backend/public:/app/backend/public
  depends_on:
   - php-fpm
  ports:
   - "8080:80"
  networks:
   - retromat

 php-fpm:
  build:
   context: .
   dockerfile: ./backend/docker/php-fpm/Dockerfile
  volumes:
   - .:/app
  depends_on:
   - db
  networks:
   - retromat

 db:
  image: mariadb
  ports:
   - 3306:3306
  environment:
   MYSQL_ROOT_PASSWORD: PaSsWoRd
  networks:
   - retromat

 redis:
  image: redis
  ports:
   - 6379:6379
  networks:
   - retromat

 phpmyadmin:
  image: phpmyadmin/phpmyadmin
  links:
   - db:db
  ports:
   - 8181:80
  networks:
   - retromat

networks:
 retromat:
  driver: bridge
