security:
    encoders:
        App\Entity\User:
            algorithm: bcrypt
    enable_authenticator_manager: true
    password_hashers:
        App\Entity\User: 'auto'
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
            algorithm: 'auto'
            cost: 15
    providers:
        user_provider:
            entity:
                class: App\Entity\User
                property: username
    role_hierarchy:
        ROLE_TRANSLATOR_EN:
            - ROLE_TRANSLATOR
        ROLE_TRANSLATOR_DE:
            - ROLE_TRANSLATOR
        ROLE_TRANSLATOR_ES:
            - ROLE_TRANSLATOR
        ROLE_TRANSLATOR_FR:
            - ROLE_TRANSLATOR
        ROLE_TRANSLATOR_NL:
            - ROLE_TRANSLATOR
        ROLE_TRANSLATOR_PL:
            - ROLE_TRANSLATOR
        ROLE_TRANSLATOR_PT-BR:
            - ROLE_TRANSLATOR
        ROLE_TRANSLATOR_RU:
            - ROLE_TRANSLATOR
        ROLE_TRANSLATOR_ZH:
            - ROLE_TRANSLATOR
        ROLE_TRANSLATOR:
            - ROLE_USER
        ROLE_ADMIN:
            - ROLE_TRANSLATOR_EN
            - ROLE_TRANSLATOR_DE
            - ROLE_TRANSLATOR_ES
            - ROLE_TRANSLATOR_FR
            - ROLE_TRANSLATOR_NL
            - ROLE_TRANSLATOR_PL
            - ROLE_TRANSLATOR_PT-BR
            - ROLE_TRANSLATOR_RU
            - ROLE_TRANSLATOR_ZH
            - ROLE_SERP_PREVIEW
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: user_provider
            custom_authenticator: App\Security\UserAuthenticator
            logout:
                path: user_logout
                target: user_login
    access_control:
         - { path: '^/[a-z]{2}/team', roles: ROLE_TRANSLATOR }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
